/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicios;

import clasesPojoS.Equipos;
import clasesPojoS.Estadisticas;
import clasesPojoS.Jugadores;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import org.hibernate.ObjectNotFoundException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author juanfdg
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpPrincipal = new javax.swing.JTabbedPane();
        jpMenuPrincipal = new javax.swing.JPanel();
        jlTituloPrincipal = new javax.swing.JLabel();
        jlIntroduccion = new javax.swing.JLabel();
        jbtnJugadores = new javax.swing.JButton();
        jbtnEquipos = new javax.swing.JButton();
        jpJugadores = new javax.swing.JPanel();
        jtpJugadores = new javax.swing.JTabbedPane();
        jpInfoJugadores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInfoEstadisticas = new javax.swing.JTable();
        jtfCodigoJugador = new javax.swing.JTextField();
        jtfNombreJugador = new javax.swing.JTextField();
        jtfEquipo = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jlDatosJugador = new javax.swing.JLabel();
        jlInfoNombre = new javax.swing.JLabel();
        jlInfoEquipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlNumeroRegistros = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jpInsertarInfo = new javax.swing.JPanel();
        jpEquipos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaInformacionEquipos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrenador 3.0");
        setResizable(false);

        jlTituloPrincipal.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jlTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloPrincipal.setText("Entrenador 3.0");

        jlIntroduccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIntroduccion.setText("Todo lo necesario para gestionar la calidad de los jugadores y equipos");

        jbtnJugadores.setText("Jugadores");
        jbtnJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJugadoresActionPerformed(evt);
            }
        });

        jbtnEquipos.setText("Equipos");
        jbtnEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuPrincipalLayout = new javax.swing.GroupLayout(jpMenuPrincipal);
        jpMenuPrincipal.setLayout(jpMenuPrincipalLayout);
        jpMenuPrincipalLayout.setHorizontalGroup(
            jpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlIntroduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpMenuPrincipalLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jbtnJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jbtnEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addContainerGap())
        );
        jpMenuPrincipalLayout.setVerticalGroup(
            jpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuPrincipalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlIntroduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(jpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnEquipos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnJugadores, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(105, 105, 105))
        );

        jtpPrincipal.addTab("Menu Principal", jpMenuPrincipal);

        jtInfoEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Temporada", "Puntos", "Asistencias", "Tapones", "Rebotes"
            }
        ));
        jtInfoEstadisticas.setEnabled(false);
        jtInfoEstadisticas.setFillsViewportHeight(true);
        jtInfoEstadisticas.setFocusable(false);
        jScrollPane1.setViewportView(jtInfoEstadisticas);

        jtfCodigoJugador.setText("Introduce el codigo del jugador");

        jtfNombreJugador.setEditable(false);

        jtfEquipo.setEditable(false);

        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jlDatosJugador.setText("DATOS DEL JUGADOR:");

        jlInfoNombre.setText("Nombre:");

        jlInfoEquipo.setText("Equipo:");

        jLabel4.setText("Numero de registros: ");

        jButton1.setText("Insertar");

        jButton2.setText("Aceptar");

        javax.swing.GroupLayout jpInfoJugadoresLayout = new javax.swing.GroupLayout(jpInfoJugadores);
        jpInfoJugadores.setLayout(jpInfoJugadoresLayout);
        jpInfoJugadoresLayout.setHorizontalGroup(
            jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInfoJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpInfoJugadoresLayout.createSequentialGroup()
                        .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInfoJugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlNumeroRegistros))
                            .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpInfoJugadoresLayout.createSequentialGroup()
                                    .addComponent(jlDatosJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfCodigoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpInfoJugadoresLayout.createSequentialGroup()
                                    .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlInfoEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlInfoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jbtnBuscar))
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        jpInfoJugadoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jbtnBuscar});

        jpInfoJugadoresLayout.setVerticalGroup(
            jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInfoJugadoresLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpInfoJugadoresLayout.createSequentialGroup()
                        .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDatosJugador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlInfoNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlInfoEquipo)))
                    .addGroup(jpInfoJugadoresLayout.createSequentialGroup()
                        .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlNumeroRegistros))
                .addGap(43, 43, 43)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpInfoJugadoresLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jbtnBuscar});

        jtpJugadores.addTab("Buscar Estadisticas", jpInfoJugadores);

        javax.swing.GroupLayout jpInsertarInfoLayout = new javax.swing.GroupLayout(jpInsertarInfo);
        jpInsertarInfo.setLayout(jpInsertarInfoLayout);
        jpInsertarInfoLayout.setHorizontalGroup(
            jpInsertarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        jpInsertarInfoLayout.setVerticalGroup(
            jpInsertarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        jtpJugadores.addTab("Insertar Nuevas Estadisticas", jpInsertarInfo);

        javax.swing.GroupLayout jpJugadoresLayout = new javax.swing.GroupLayout(jpJugadores);
        jpJugadores.setLayout(jpJugadoresLayout);
        jpJugadoresLayout.setHorizontalGroup(
            jpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpJugadores)
        );
        jpJugadoresLayout.setVerticalGroup(
            jpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpJugadores)
        );

        jtpPrincipal.addTab("Jugadores", jpJugadores);

        jpEquipos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpEquiposComponentShown(evt);
            }
        });

        jtaInformacionEquipos.setEditable(false);
        jtaInformacionEquipos.setColumns(20);
        jtaInformacionEquipos.setRows(5);
        jScrollPane2.setViewportView(jtaInformacionEquipos);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACIÓN DE LOS EQUIPOS");

        javax.swing.GroupLayout jpEquiposLayout = new javax.swing.GroupLayout(jpEquipos);
        jpEquipos.setLayout(jpEquiposLayout);
        jpEquiposLayout.setHorizontalGroup(
            jpEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpEquiposLayout.setVerticalGroup(
            jpEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtpPrincipal.addTab("Equipos", jpEquipos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJugadoresActionPerformed
        jtpPrincipal.setSelectedComponent(jpJugadores);
        jtpJugadores.setSelectedComponent(jpInfoJugadores);
    }//GEN-LAST:event_jbtnJugadoresActionPerformed

    private void jbtnEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEquiposActionPerformed
        jtpPrincipal.setSelectedComponent(jpEquipos);
        SessionFactory sesion = NewHibernateUtil.getSessionFactory();
        Session sesionCreada = sesion.openSession();
        StringBuilder sb = new StringBuilder();
        String s = System.getProperty("line.separator");
        Query q = sesionCreada.createQuery("from Equipos");
        List<Equipos> listaEquipos = q.list();
        Iterator<Equipos> iteraEquipos = listaEquipos.iterator();
        sb.append("Número de equipos: " + listaEquipos.size() + s);
        while (iteraEquipos.hasNext()) {
            sb.append("==============================================" + s);
            Equipos equipo = iteraEquipos.next();
            sb.append("Equipo: " + equipo.getNombre() + s);
            for (Iterator<Jugadores> it = equipo.getJugadoreses().iterator(); it.hasNext();) {
                Jugadores jugador = it.next();
                String hql = "select avg(puntosPorPartido) "
                        + "from Estadisticas e "
                        + "where e.id.jugador = :codJugador";
                q = sesionCreada.createQuery(hql);
                q.setParameter("codJugador", jugador.getCodigo());
                Double puntuacionMedia = (Double) q.uniqueResult();
                if (puntuacionMedia == null) {
                    puntuacionMedia = 0D;
                }

                sb.append(jugador.getCodigo() + ", "
                        + jugador.getNombre() + ": "
                        + puntuacionMedia.toString() + s);

            }
            sb.append(". . . . . . . . . . . . . . ." + s);
        }
        jtaInformacionEquipos.setText(sb.toString());
        sesionCreada.close();
    }//GEN-LAST:event_jbtnEquiposActionPerformed

    private void jpEquiposComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpEquiposComponentShown
        SessionFactory sesion = NewHibernateUtil.getSessionFactory();
        Session sesionCreada = sesion.openSession();
        StringBuilder sb = new StringBuilder();
        String s = System.getProperty("line.separator");
        Query q = sesionCreada.createQuery("from Equipos");
        List<Equipos> listaEquipos = q.list();
        Iterator<Equipos> iteraEquipos = listaEquipos.iterator();
        sb.append("Número de equipos: " + listaEquipos.size() + s);
        while (iteraEquipos.hasNext()) {
            sb.append("==============================================" + s);
            Equipos equipo = iteraEquipos.next();
            sb.append("Equipo: " + equipo.getNombre() + s);
            for (Iterator<Jugadores> it = equipo.getJugadoreses().iterator(); it.hasNext();) {
                Jugadores jugador = it.next();
                String hql = "select avg(puntosPorPartido) "
                        + "from Estadisticas e "
                        + "where e.id.jugador = :codJugador";
                q = sesionCreada.createQuery(hql);
                q.setParameter("codJugador", jugador.getCodigo());
                Double puntuacionMedia = (Double) q.uniqueResult();
                if (puntuacionMedia == null) {
                    puntuacionMedia = 0D;
                }

                sb.append(jugador.getCodigo() + ", "
                        + jugador.getNombre() + ": "
                        + puntuacionMedia.toString() + s);

            }
            sb.append(". . . . . . . . . . . . . . ." + s);
        }
        jtaInformacionEquipos.setText(sb.toString());
        sesionCreada.close();
    }//GEN-LAST:event_jpEquiposComponentShown

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        if (jtfCodigoJugador.getText().length() > 0) {
            try {
                SessionFactory sesion = NewHibernateUtil.getSessionFactory();
                Session sesionCreada = sesion.openSession();
                Jugadores jugador = (Jugadores) sesionCreada.load(
                        Jugadores.class,
                        Integer.parseInt(jtfCodigoJugador.getText())
                );
                jtfNombreJugador.setText(jugador.getNombre());
                jtfEquipo.setText(jugador.getEquipos().getNombre());
                Set<Estadisticas> estadisticas = jugador.getEstadisticases();
                DefaultTableModel dftm = (DefaultTableModel)jtInfoEstadisticas.getModel();
                dftm.setNumRows(estadisticas.size());
                jtInfoEstadisticas.setModel(dftm);
                int row = 0;
                for (Iterator it = estadisticas.iterator(); it.hasNext(); row++) {
                    Estadisticas estadistica = (Estadisticas) it.next();
                    jtInfoEstadisticas.setValueAt(estadistica.getId().getTemporada(),row, 0);
                    jtInfoEstadisticas.setValueAt(estadistica.getPuntosPorPartido(),row, 1);
                    jtInfoEstadisticas.setValueAt(estadistica.getAsistenciasPorPartido(),row, 2);
                    jtInfoEstadisticas.setValueAt(estadistica.getTaponesPorPartido(),row, 3);
                    jtInfoEstadisticas.setValueAt(estadistica.getRebotesPorPartido(),row, 4);
                }
                jlNumeroRegistros.setText(String.valueOf(estadisticas.size()));
                sesionCreada.close();
            } catch (ObjectNotFoundException onfe) {
                System.out.println("El jugador introducido no existe");
            }
        }else{
                
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnEquipos;
    private javax.swing.JButton jbtnJugadores;
    private javax.swing.JLabel jlDatosJugador;
    private javax.swing.JLabel jlInfoEquipo;
    private javax.swing.JLabel jlInfoNombre;
    private javax.swing.JLabel jlIntroduccion;
    private javax.swing.JLabel jlNumeroRegistros;
    private javax.swing.JLabel jlTituloPrincipal;
    private javax.swing.JPanel jpEquipos;
    private javax.swing.JPanel jpInfoJugadores;
    private javax.swing.JPanel jpInsertarInfo;
    private javax.swing.JPanel jpJugadores;
    private javax.swing.JPanel jpMenuPrincipal;
    private javax.swing.JTable jtInfoEstadisticas;
    private javax.swing.JTextArea jtaInformacionEquipos;
    private javax.swing.JTextField jtfCodigoJugador;
    private javax.swing.JTextField jtfEquipo;
    private javax.swing.JTextField jtfNombreJugador;
    private javax.swing.JTabbedPane jtpJugadores;
    private javax.swing.JTabbedPane jtpPrincipal;
    // End of variables declaration//GEN-END:variables
}
